name: Default workflow

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  FormattingCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Check formatting with black
        uses: psf/black@stable
        with:
          src: "./app/"
          options: "--check"
  Integration-Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Install dependencies
        run: >
          pip install -r requirements.txt -q 
      - name: Run Tests
        id: pytest
        run: |
          pytest tests/integration
  Unit-Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Install dependencies
        run: >
          pip install -r requirements.txt -q 
      - name: Run Tests
        id: pytest
        run: |
          pytest -n 5 --cov --cov-config=.coveragerc tests/unit