name: Default workflow

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  FormattingCheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Check formatting with black
        uses: psf/black@stable
        with:
          src: "./app/"
          options: "--check"
  Integration-Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Install dependencies
        run: >
          pip install -r requirements.txt -q 
      - name: Run Tests
        id: pytest
        run: |
          pytest --cov --cov-config=.coveragerc tests/integration
      - name: Build coverage file
        run: |
          pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
  Unit-Tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          architecture: "x64"
      - name: Install dependencies
        run: >
          pip install -r requirements.txt -q 
      - name: Run Tests
        id: pytest
        run: |
          pytest -n 5 --cov --cov-config=.coveragerc tests/unit
  